import 'package:flutter/material.dart';
import 'package:research_ai/utils/app_theme.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    const body = '''By using Research AI, you agree to our Terms of Service and Privacy Policy.

1. Use of Service
You agree to use this app for lawful purposes only and not to misuse the AI features or upload content you do not have the right to share.

2. AI-Generated Content
Summaries, answers and citations are generated by AI and may contain errors. Always verify important information against the original sources before relying on it.

3. Your Content
You retain ownership of the documents you upload. We process them only to provide the app's features.

4. Privacy
You can control chat history and analytics from Privacy Settings at any time.

5. Changes
We may update these terms from time to time. Continued use of the app means you accept the latest version.''';
    return Scaffold(
      appBar: AppBar(title: const Text('Terms & Conditions')),
      body: const SingleChildScrollView(
        padding: kPad,
        child: Text(body,
            style: TextStyle(color: kInk, height: 1.7, fontSize: 14.5)),
      ),
    );
  }
}
